### ISSUE TITLE
'Loading image...' gets displayed but no image gets displayed Mac OS High Sierra

### ISSUE THREAD

**Issue by AndrewMagerman** [hao-lee/Graphvizer#8] opened 2019-02-04 10:06 UTC
Hi hao-lee,

Excellent initiative! I've been dreaming of something like this for ages. I tried to install it on my Mac (High Sierra 10.13.6). The Graph does not get displayed.

I though it might be a permissions issue for the temporary folder, so I created a specific temp folder in the user settings, but Graphvizer is still trying to access the system temp folder.

my 'dot' is on the path, I can type 'dot - v' in the Terminal and I get a version.

Would love to get this working on my machine.

Thanks, 
Andrew Magerman

![screen shot 2019-02-04 at 11 01 43](https://user-images.githubusercontent.com/1528800/52201614-50e0ce80-286c-11e9-8688-eaaeda0360a8.png)
![screen shot 2019-02-04 at 11 01 28](https://user-images.githubusercontent.com/1528800/52201615-50e0ce80-286c-11e9-80db-43e1ab649f94.png)

**Comment by kwoodham** [comment] 2019-02-06 21:38
Same issue for me on Windows 10 - I do not see a `graphvizer.png` generated in the system temp folder, and the "Loading image..." displays in Sublime Text. I'm confirmed that `dot` is in the Windows path.

**Comment by hao-lee** [comment] 2019-02-07 08:59
Hi,
It seems that you didn't set the syntax to `Graphviz (Dot)`. You can do this by `View -> Syntax` menu or clicking the bottom right corner of Sublime Text window.

**Comment by hao-lee** [comment] 2019-02-07 09:04
@AndrewMagerman 
Hi,
It seems that you didn't set the syntax to `Graphviz (Dot)`. You can do this by `View -> Syntax` menu or clicking the bottom right corner of Sublime Text window.

**Comment by hao-lee** [comment] 2019-02-07 09:06
@kwoodham 
Hi,
You can press `Ctrl + ~` to open the sublime console. If these are some errors, you can post them here to help me debug plugin. Thanks!

**Comment by AndrewMagerman** [comment] 2019-02-07 10:18
Hi haolee, 

It's working now - I think I needed to reboot completely for it to work.



The only thing that is still weird is that the image_dir attribute in the settings (see picture) is stored in the default temp folder, and not where I specified it.



Apart from that, it's awesome! Many thanks!

Best Regards,
Andrew Magerman

Magerman GmbH, Im Marbach 53, 8800 Thalwil, Tel/Fax: +41 43 540 99 67
http://www.magerman.com

**Comment by hao-lee** [comment] 2019-02-07 12:11
If  the `graphviztemp` directory does exist, I think it may because this directory doesn't have permission to write.

**Comment by AndrewMagerman** [comment] 2019-02-07 13:31
Hi haolee, it's apparently not a permissions issue.

I've noticed something else: Sometimes I open a dot file and 'loading image' displays, and I only get the image displaying when I make a change on the file. Is that expected behaviour?

Best Regards,
Andrew Magerman

Magerman GmbH, Im Marbach 53, 8800 Thalwil, Tel/Fax: +41 43 540 99 67
http://www.magerman.com

**Comment by kwoodham** [comment] 2019-02-07 13:56
Andrew's experience is the same as mine: the plugin is working fine now - I found that I needed to make an edit to the dot file before the image was rendered (something as simple as deleting a ";" and restoring it) - So it appears that the dot command is kicked off by a modification to the dot.

This isn't a problem for me now that I understand the solution.  Thank you for your excellent work, hao-lee!

Kurt

**Comment by hao-lee** [comment] 2019-02-08 01:21
@AndrewMagerman @kwoodham 
Hi, This is indeed a problem. Sublime Text doesn't provide an api to watch syntax changing, so the image rendering can't be triggered by setting syntax to `Graphviz (Dot)`. For now, the only way to trigger the rendering process is editing the content.
I have planned to fix this problem using some tricks, it will be released in next release. :smirk:

**Comment by AndrewMagerman** [comment] 2019-02-08 08:07
Hi hao-lee,



I made a mistake in the configuration - the directory I inputted did not exists. Doh.

But I would recommend you changing get_image_file to log out 'directory not found: {image_dir} to help the debugging/installation.
# Generated image file
def get_image_file():
   image_dir = None
   settings = sublime.load_settings("Graphvizer.sublime-settings")
   image_dir = settings.get("image_dir")
   if (image_dir is None) or not os.path.exists(image_dir) \
                  or not os.access(image_dir, os.W_OK):
      image_dir = tempfile.gettempdir()
   return os.path.join(image_dir, "graphvizer.png")
Best Regards,
Andrew Magerman

Magerman GmbH, Im Marbach 53, 8800 Thalwil, Tel/Fax: +41 43 540 99 67
http://www.magerman.com

**Comment by hao-lee** [comment] 2019-02-08 09:06
@AndrewMagerman 
Hi AndrewMagerman, thanks for your suggestion. This is indeed useful and will be enhanced in the next release.

**Closed as completed** 2019-02-17 15:16 UTC
Labels: feature request

**Comment by hao-lee** [comment] 2019-02-17 15:24
@AndrewMagerman Hi, check the latest release. :smirk: It's perfect!

**Comment by AndrewMagerman** [comment] 2019-02-17 17:44
Nice!

Well done!

Best Regards,
Andrew Magerman

**Comment by Gerst20051** [comment] 2019-03-29 17:09
I'm still seeing this issue of needing to edit the contents for the image to appear.

**Comment by hao-lee** [comment] 2019-03-30 06:23
@Gerst20051 Try to update the plugin to the latest version

**Comment by Gerst20051** [comment] 2019-03-30 07:13
@hao-lee I had just installed it for the first time today.

**Comment by Gerst20051** [comment] 2019-03-30 07:13
Let me know if theres any more details I can provide.

**Comment by hao-lee** [comment] 2019-03-30 10:55
> I'm still seeing this issue of needing to edit the contents for the image to appear.

@Gerst20051 
Hi, you can describe the steps that can reproduce this issue. If the image is not rendered, you can also see if there are some errors in *Graphvizer Panel* (`Ctrl+Shift+x` to open it) or *Sublime console* (`Ctrl+~` to open it). Thanks.

**Comment by cpenny42** [comment] 2019-04-30 17:14
I am having this exact same issue. 

Here is my dot file:
```dot
digraph test {
	foo -> bar
	foo -> baz
	bar -> baz
}
```
And my settings:
```jsonc
{
	// "dot_cmd_path" is the path of dot command. Here are some examples.
	// For Windows: "D:\\Graphviz\\bin\\dot.exe"
	// For Linux: "/usr/bin/dot"
	// For OSX: "/usr/bin/dot"
	// If you have added this path to the PATH environment variable, you can
	// use "dot" instead of the full absolute path.
	"dot_cmd_path": "dot",
	// If the dot command takes more than `dot_timeout` seconds, it will be
	// terminated. The default value is 3 seconds.
	"dot_timeout": 3,
	// "show_image_with" controls how to show the image.
	// The default value is "layout", so the image will be shown in a separated
	// layout by default. If you want to show it in a new window instead,
	// change the following value to "window". If you just want to show the image
	// in a new tab, change the value to "tab".
	"show_image_with": "layout",
	// "image_dir" controls where the image is saved. If the value is "",
	// system temporary directory is used. You can set it to other directory.
	// Example for Windows: "E:\\homework\\image\\"
	// Example for Linux/OSX: "/home/haolee/image/"
	"image_dir": "/Users/chrispenny/Developer/temp",
	// The default behavior is rendering the image in real time.
	// If set to false, the image will only be rendered when the file is saved.
	"render_in_realtime": true
}
```
Note that I have correctly installed graphviz and can run `dot -v` in the terminal (and can successfully render my test file). I installed the sublime text package today, so I imagine it is at the latest version.

When I open the console, I see this error message only the first time it tries to process a file:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/chrispenny/Library/Application Support/Sublime Text 3/Installed Packages/Graphvizer.sublime-package/graphvizer.py", line 67, in dot_thread
    with open(file=self.dot_file, mode="w", encoding="utf-8") as fd:
TypeError: invalid file: None
```
I can imagine that the python script getting `None` as the file would be an issue!

Subsequent times I try closing and opening the graphvizer window (`ctrl-shift-g`) I see this in the console: `decode image failed`

However, when I open the graphvizer panel, I see this message: `[2019-04-30 12:47:47] - No error occurred`

I have tried leaving my `image_dir` blank as well as trying all sorts of different directories (based on the advice above), but no luck.

Here is a screenshot:
![Graphvizer Error Screenshot](https://i.imgur.com/atvU3fp.png)

Hope this helps!

**Comment by cpenny42** [comment] 2019-04-30 17:22
Forgot to mention I am on macOS 10.14 (Mojave)

**Comment by panchtox** [comment] 2019-08-01 19:46
Same issue on Mojave 10.14.5
Thanks

**Comment by hao-lee** [comment] 2019-08-02 01:51
@panchtox 
Hi, you can try to update to the latest version. If the problem still exists, press `CMD+`` and see if there are some errors in there. Thanks.
